### ISSUE TITLE
Unable to start service on Mac

### ISSUE THREAD

**Issue by tonyjiang** [colinsurprenant/raad#18]
I can't start a simple service. Here is the output:

$ ruby lib/scheduler/runner.rb start

> > Raad service wrapper v0.5.0 starting
> > [4738:INFO] 2013-02-03 21:43:30 :: starting runner service in development mode
> > [4738:INFO] 2013-02-03 21:43:30 :: stopping runner service
> > [4738:INFO] 2013-02-03 21:43:30 :: >> Raad service wrapper stopped

**Comment by tonyjiang** [comment]
It turns out to have something to do with Rufus scheduler, which I use to execute a script at certain interval. After creating a scheduler and arranging it to run at certain times, you have to call 'join' on the scheduler for it to stay on.

**Comment by colinsurprenant** [comment]
Right. Correct me if I'm wrong but I assume that without calling join, your `start` method was returning right away? This is by design in raad, your start method should not return until your deamon has finished its work or that the `stop` method has been called.
