### ISSUE TITLE
Support to pass parameters

### ISSUE THREAD

**Issue by net1957** [colinsurprenant/raad#6]
It would be nice to pass parameters to the service.

ex: before radd I did run the ruby with "ruby GetResponseByPop3.rb test"
with raad  I run it with "ruby GetResponseByPop3.rb start"

but it would be nice to add -- test to pass my parameters

any idea , or I am wrong ?

**Comment by colinsurprenant** [comment]
yes, everything is there to pass parameters, just not documented, sorry! I'll add the info a bit later tonight for you. hang in there :)

**Comment by colinsurprenant** [comment]
btw, you could also use the -e, --environment NAME  option and within your service you can test for this environment NAME using Raad.env

NAME can be anything, with specific support for "development", "stage", "production" and "test".

for example, if you run it with "ruby GetResponseByPop3.rb -e test start" you can use:
if Raad.env == :test ...
if Raad.test? ...

or with any other NAME like ""ruby GetResponseByPop3.rb -e foobar start""
if Raad.env == :foobar ...

but you won't get Raad.foobar? ... the #production? #development? #stage? and #test? methods are predefined.

**Comment by colinsurprenant** [comment]
Ok, I've updated the README with documentation for the environment option and custom command line options. 

Have fun. Let me know if you have questions/issues.
